/**
 * LearnTrack - Supabase Integration & RLS Automated Test Suite
 *
 * Verifies:
 * 1. Environment validation
 * 2. Supabase client initialization
 * 3. PostgreSQL database connectivity
 * 4. User Signup & Auth lifecycle
 * 5. Automatic Profile & Student record creation trigger
 * 6. User Login & Session retrieval
 * 7. Authenticated Database Writes
 * 8. Authenticated Database Reads & Data Persistence
 * 9. RLS & Multi-tenant User Isolation
 * 10. User Sign Out & Session invalidation
 */

import { createClient } from "@supabase/supabase-js";
import { validateSupabaseEnv } from "../../env";

function assert(condition: boolean, message: string) {
  if (!condition) {
    console.error(`❌ FAILED: ${message}`);
    throw new Error(`Assertion failed: ${message}`);
  }
  console.log(`  ✓ ${message}`);
}

async function runTestSuite() {
  console.log("==================================================================");
  console.log("🚀 STARTING LEARNTRACK REAL SUPABASE INTEGRATION TEST SUITE");
  console.log("==================================================================\n");

  // 1. Environment Validation
  console.log("TEST 1: Environment Validation & Configuration Integrity");
  const { supabaseUrl, supabaseAnonKey } = validateSupabaseEnv();
  assert(Boolean(supabaseUrl && supabaseAnonKey), "Supabase URL and anon key loaded from environment");
  assert(supabaseUrl.startsWith("https://"), "Supabase URL is a valid HTTPS endpoint");
  assert(!supabaseUrl.includes("mock-instance"), "No mock-instance placeholder in URL");
  assert(!supabaseUrl.includes("placeholder-project"), "No placeholder-project in URL");
  assert(!supabaseAnonKey.includes("placeholder"), "No placeholder anon key in environment");

  // 2. Client Initialization
  console.log("\nTEST 2: Supabase Client Initialization");
  const anonClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  assert(Boolean(anonClient), "Supabase client successfully initialized");

  // 3. Database Ping & Schema Verification
  console.log("\nTEST 3: Live PostgreSQL Connectivity & Ping");
  const pingStart = Date.now();
  const { count: profileCount, error: pingError } = await anonClient
    .from("profiles")
    .select("id", { count: "exact", head: true });

  const latency = Date.now() - pingStart;
  assert(!pingError, `Live PostgreSQL ping succeeded without error (latency: ${latency}ms)`);
  console.log(`  ✓ Verified database connectivity to Supabase (${profileCount ?? 0} existing profiles)`);

  // 4. Real User Signup Test
  console.log("\nTEST 4: Real User Authentication - Signup Lifecycle");
  const testEmail = `test.student.${Date.now()}@learntrack.dev`;
  const testPassword = `SecureP@ssword${Date.now()}!`;
  const testFullName = `Test Student ${Date.now()}`;

  const { data: signUpData, error: signUpError } = await anonClient.auth.signUp({
    email: testEmail,
    password: testPassword,
    options: {
      data: {
        full_name: testFullName,
      },
    },
  });

  assert(!signUpError, `User signup succeeded in Supabase Auth (${testEmail})`);
  assert(Boolean(signUpData.user?.id), `Supabase Auth assigned genuine UUID: ${signUpData.user?.id}`);
  const testUserId = signUpData.user!.id;

  // 5. User Login & Session Verification
  console.log("\nTEST 5: Real User Authentication - Login & Session Retrieval");
  const authClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: signInData, error: signInError } = await authClient.auth.signInWithPassword({
    email: testEmail,
    password: testPassword,
  });

  assert(!signInError, "User successfully authenticated with Supabase signInWithPassword");
  assert(Boolean(signInData.session?.access_token), "Real JWT access token generated by Supabase Auth");
  assert(signInData.user?.id === testUserId, "Authenticated session user ID matches signup UUID");

  // 6. Automatic Profile and Student Trigger Check
  console.log("\nTEST 6: Automatic Profile & Student Creation (handle_new_user Trigger)");
  // Allow trigger a moment if asynchronous
  await new Promise((r) => setTimeout(r, 800));

  const { data: profileRow, error: profileErr } = await authClient
    .from("profiles")
    .select("*")
    .eq("id", testUserId)
    .single();

  assert(!profileErr, "User profile row exists in public.profiles table");
  assert(profileRow.email === testEmail, "Profile email matches registered account");

  const { data: studentRow, error: studentErr } = await authClient
    .from("students")
    .select("*")
    .eq("profile_id", testUserId)
    .single();

  assert(!studentErr, "Student record exists in public.students table linked via profile_id");
  assert(Boolean(studentRow.id), `Student record assigned genuine ID: ${studentRow.id}`);
  const testStudentId = studentRow.id;

  // 7. Authenticated Database Write Test
  console.log("\nTEST 7: Authenticated Database Writes (Subjects & Academic Records)");
  const { data: subjectData, error: subjectError } = await authClient
    .from("subjects")
    .insert([
      {
        student_id: testStudentId,
        subject_name: "Computer Architecture",
        subject_code: `CS-${Date.now().toString().slice(-4)}`,
        credits: 4,
        semester: 1,
      },
    ])
    .select()
    .single();

  assert(!subjectError, "Successfully inserted subject record into public.subjects");
  assert(Boolean(subjectData?.id), `Subject created with ID: ${subjectData?.id}`);

  // Insert academic record
  const { data: recordData, error: recordError } = await authClient
    .from("academic_records")
    .insert([
      {
        student_id: testStudentId,
        subject_id: subjectData.id,
        academic_year: "2026-2027",
        semester: 1,
        attendance_percentage: 95.0,
        assignment_marks: 19.5,
        internal_marks: 28.0,
        exam_marks: 45.0,
        total_marks: 92.5,
        grade: "A+",
        grade_point: 9.5,
      },
    ])
    .select()
    .single();

  assert(!recordError, "Successfully inserted academic record into public.academic_records");
  assert(Boolean(recordData?.id), `Academic record created with ID: ${recordData?.id}`);

  // 8. Authenticated Database Read Test (Persistence Verification)
  console.log("\nTEST 8: Authenticated Database Reads & Data Persistence");
  const { data: queriedRecords, error: queryError } = await authClient
    .from("academic_records")
    .select("*, subject:subjects(*)")
    .eq("student_id", testStudentId);

  assert(!queryError, "Successfully queried academic records with joined subject relation");
  assert(Boolean(queriedRecords && queriedRecords.length === 1), "Persisted record count matches inserted count (1)");
  assert(queriedRecords![0].grade === "A+", "Queried grade matches persisted value ('A+')");
  assert(queriedRecords![0].subject.subject_name === "Computer Architecture", "Joined relation retrieved accurately from Supabase");

  // 9. Row Level Security & User Isolation Test
  console.log("\nTEST 9: Row Level Security (RLS) & Multi-Tenant Isolation");
  // Unauthenticated client (no session) attempting to read User A's subjects
  const unauthClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: anonReadData, error: anonReadErr } = await unauthClient
    .from("subjects")
    .select("*")
    .eq("student_id", testStudentId);

  assert(!anonReadErr, "Anon query executed against RLS-protected table");
  assert(Boolean(anonReadData && anonReadData.length === 0), "Unauthenticated client cannot view student subjects (0 rows returned via RLS)");

  // Create second user (User B) to test cross-tenant isolation
  const userBEmail = `bob.${Date.now()}@learntrack.dev`;
  const userBPassword = `BobSecurePassword${Date.now()}!`;
  const userBClient = createClient(supabaseUrl, supabaseAnonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: _userBSignUp, error: userBSignUpErr } = await userBClient.auth.signUp({
    email: userBEmail,
    password: userBPassword,
  });
  assert(!userBSignUpErr, "User B signup succeeded");

  const { error: userBSignInErr } = await userBClient.auth.signInWithPassword({
    email: userBEmail,
    password: userBPassword,
  });
  assert(!userBSignInErr, "User B signed in successfully");

  // User B attempting to view User A's data
  const { data: userBSubjects, error: userBReadErr } = await userBClient
    .from("subjects")
    .select("*")
    .eq("student_id", testStudentId);

  assert(!userBReadErr, "User B query executed without error");
  assert(userBSubjects?.length === 0, "User B CANNOT view User A's subject data (RLS tenant isolation enforced)");

  // User B attempting to mutate User A's subject
  const { data: unauthorizedUpdate } = await userBClient
    .from("subjects")
    .update({ subject_name: "Hacked Subject" })
    .eq("id", subjectData.id)
    .select();

  assert(!unauthorizedUpdate || unauthorizedUpdate.length === 0, "User B CANNOT mutate User A's data (0 rows modified)");

  // 10. Real Sign Out Test
  console.log("\nTEST 10: Supabase Sign Out & Session Termination");
  const { error: signOutErr } = await authClient.auth.signOut();
  assert(!signOutErr, "authClient.auth.signOut() terminated Supabase session");

  // Post-logout check
  const { data: postLogoutSession } = await authClient.auth.getSession();
  assert(!postLogoutSession.session, "Session is null following signOut");

  console.log("\n==================================================================");
  console.log("🎉 ALL 10 SUPABASE INTEGRATION & RLS SECURITY TESTS PASSED!");
  console.log("==================================================================\n");
}

runTestSuite().catch((err) => {
  console.error("\n❌ TEST SUITE FAILED WITH ERROR:", err);
  process.exit(1);
});
