"use client";

import React from "react";
import {
  Sparkles,
  RotateCcw,
  Check,
  CheckCircle2,
  AlertTriangle,
  Info,
  Calendar,
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Tooltip } from "@/components/ui/Tooltip";

export interface CandidateModelsWorkspaceProps {
  candidates: any[];
  productionRmse?: number;
  onOpenPromote: (candidateVersion: string) => void;
  onOpenRollback: () => void;
  onOpenDetails: (candidate: any) => void;
  onGenerateCandidate: () => void;
  isRetraining: boolean;
}

export function CandidateModelsWorkspace({
  candidates = [],
  productionRmse = 7.677,
  onOpenPromote,
  onOpenRollback,
  onOpenDetails,
  onGenerateCandidate,
  isRetraining,
}: CandidateModelsWorkspaceProps) {
  return (
    <div className="bg-white border border-[#E2E8F0] rounded-[16px] shadow-xs overflow-hidden">
      {/* Header with Title and Rollback Action */}
      <div className="p-5 sm:p-6 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0">
              <Sparkles className="w-4.5 h-4.5" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">
                Registry Queue
              </span>
              <h2 className="text-base font-bold text-slate-900 tracking-tight">
                Model Candidates
              </h2>
            </div>
            <Tooltip content="Candidate models generated by recent retraining pipelines held in verification staging.">
              <span className="cursor-help text-slate-400 hover:text-slate-600">
                <Info className="w-3.5 h-3.5" />
              </span>
            </Tooltip>
          </div>
          <p className="text-xs text-slate-500 mt-1 pl-10">
            Candidate models awaiting verification and promotion eligibility. Models must satisfy regression thresholds before promotion.
          </p>
        </div>

        {/* Top-Right: Rollback Action */}
        <div className="flex items-center gap-2 self-start sm:self-auto shrink-0 pl-10 sm:pl-0">
          <Button
            variant="outline"
            size="sm"
            onClick={onOpenRollback}
            className="h-9 px-3.5 rounded-[9px] text-xs font-semibold text-slate-700 hover:text-slate-900 border-[#E2E8F0] hover:border-slate-300"
            leftIcon={<RotateCcw className="w-3.5 h-3.5 text-slate-500" />}
          >
            Rollback Options
          </Button>
        </div>
      </div>

      {/* Candidates Grid or Polished Empty State */}
      <div className="p-5 sm:p-6">
        {candidates.length > 0 ? (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {candidates.map((cand, idx) => {
              const candRmse = cand.test_metrics?.rmse ?? 7.677;
              const candMae = cand.test_metrics?.mae ?? 4.494;
              const candR2 = cand.test_metrics?.r2 ?? 0.8392;
              const isBetterOrEqual = candRmse <= productionRmse;
              const formattedDate = cand.created_at
                ? new Date(cand.created_at).toLocaleDateString("en-US", {
                    month: "short",
                    day: "numeric",
                    year: "numeric",
                  })
                : "Recent";

              return (
                <div
                  key={cand.candidate_version || idx}
                  className="rounded-[14px] border border-[#E2E8F0] bg-[#F8FAFC]/50 hover:bg-white hover:border-blue-300 hover:shadow-sm transition-all duration-180 p-5 flex flex-col justify-between space-y-4"
                >
                  {/* Top: Version & Status */}
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                          Candidate Version
                        </span>
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-mono font-bold bg-blue-50 text-blue-700 border border-blue-200">
                          {cand.candidate_version}
                        </span>
                      </div>
                      <h3 className="text-sm font-bold text-slate-900 mt-1">
                        {cand.model_type || "Linear Regression (Ridge)"}
                      </h3>
                      <p className="text-[11px] text-slate-500 font-mono mt-0.5">
                        Dataset: v{cand.dataset_version || "1.0.0"} · Run: {cand.run_id ? cand.run_id.slice(0, 8) : "Active"}
                      </p>
                    </div>

                    {/* Regression Check Badge */}
                    <div className="shrink-0">
                      {isBetterOrEqual ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                          Regression: PASSED
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] font-semibold bg-amber-50 text-amber-700 border border-amber-200">
                          <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
                          ELEVATED RMSE
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Comparative Metrics Grid */}
                  <div className="grid grid-cols-3 gap-2.5 bg-white rounded-xl p-3.5 border border-slate-200/80 shadow-2xs text-xs">
                    <div>
                      <span className="text-[10px] font-bold text-slate-400 uppercase block tracking-wider">
                        Candidate RMSE
                      </span>
                      <span className="text-base font-bold font-mono text-slate-900 mt-0.5 block">
                        {candRmse} pts
                      </span>
                      <span className="text-[10px] text-slate-400 font-mono block">
                        MAE: {candMae} pts
                      </span>
                    </div>

                    <div>
                      <span className="text-[10px] font-bold text-slate-400 uppercase block tracking-wider">
                        Prod Baseline
                      </span>
                      <span className="text-base font-semibold font-mono text-slate-600 mt-0.5 block">
                        {productionRmse} pts
                      </span>
                    </div>

                    <div>
                      <span className="text-[10px] font-bold text-slate-400 uppercase block tracking-wider">
                        Candidate R²
                      </span>
                      <span className="text-base font-bold font-mono text-slate-900 mt-0.5 block">
                        {candR2}
                      </span>
                    </div>
                  </div>

                  {/* Footer Actions & Metadata */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-1 border-t border-slate-100">
                    <div className="flex items-center gap-1.5 text-[11px] text-slate-500 font-mono">
                      <Calendar className="w-3 h-3 text-slate-400" />
                      <span>Trained: {formattedDate}</span>
                    </div>

                    <div className="flex items-center gap-2">
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => onOpenDetails(cand)}
                        className="h-8 px-2.5 text-xs text-slate-600 hover:text-slate-900 border-[#E2E8F0]"
                      >
                        Inspect Model
                      </Button>

                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => onOpenPromote(cand.candidate_version)}
                        className="h-8 px-3.5 text-xs font-semibold bg-emerald-600 hover:bg-emerald-700 text-white shadow-2xs"
                        leftIcon={<Check className="w-3.5 h-3.5" />}
                      >
                        Promote to Production
                      </Button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="py-12 flex flex-col items-center justify-center text-center p-6 border border-dashed border-slate-200 rounded-xl bg-slate-50/50">
            <Sparkles className="w-9 h-9 text-slate-300 mb-2" />
            <h3 className="text-sm font-bold text-slate-800">
              No candidate models currently held in registry
            </h3>
            <p className="text-xs text-slate-500 mt-1 max-w-sm">
              Candidate models will appear after a successful retraining pipeline run and satisfy regression protection.
            </p>
            <div className="mt-4">
              <Button
                variant="secondary"
                size="sm"
                onClick={onGenerateCandidate}
                disabled={isRetraining}
                className="text-xs text-blue-600 border-blue-200 hover:bg-blue-50"
              >
                Generate New Candidate Model
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
